version: '3.9'

# Define services (containers) that will run as part of the microservices stack.
services:

  postgres:
    image: postgres
    ports:
      - "5434:5432"
    container_name: postgres-inventory
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - PGDATA= /data/postgres
      #- POSTGRES_DB=inventory-service
    volumes:
      - ./data/inventory:/var/lib/postgresql/data  # The database will persist data here on the host machine.
      - ./init/inventory/init.sql:/docker-entrypoint-initdb.d/init.sql

  #postgres:
  #  image: postgres
  #  ports:
  #    - "5433:5432"
  #  container_name: postgres-single
  #  environment:
  #    - POSTGRES_USER=admin
  #    - POSTGRES_PASSWORD=password
  #  volumes:
  #    - ./data/order:/var/lib/postgresql/data  # The database will persist data here on the host machine.
  #    - ./init/order/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    container_name: pgadmin-single
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.ca
      - PGADMIN_DEFAULT_PASSWORD=password